- name: Extract Executables from PCAP using tshark
  hosts: servers
  tasks:
    - name: Install required tools (tshark)
      apt:
        name:
          - tshark
        state: present
        update_cache: yes

    - name: Ensure PCAP file exists
      stat:
        path: /path/to/captured.pcap
      register: pcap_file

    - name: Create extracted_files directory
      file:
        path: /tmp/extracted_files
        state: directory

    - name: Extract objects from PCAP with tshark
      command: tshark -r /path/to/captured.pcap --export-objects http,/tmp/extracted_files/
      when: pcap_file.stat.exists

    - name: Identify executable files
      shell: "file /tmp/extracted_files/* | grep 'executable'"
      register: exec_files
      when: pcap_file.stat.exists

    - name: Check if any executable files were found
      fail:
        msg: "No executable files found in /tmp/extracted_files/"
      when: exec_files.stdout_lines | length == 0

    - name: Transfer executable files to Manage node
      command: scp {{ item }} user@manage-node:/destination/path/
      with_items: "{{ exec_files.stdout_lines }}"
      when: exec_files.stdout_lines | length > 0
