---
- name: Extract executable from PCAP file on Control Node
  hosts: servers  # Ensure your inventory contains this group (servers)
  become: yes
  tasks:
    - name: Update apt cache and install tshark
      apt:
        name: tshark
        state: present
        update_cache: yes

    - name: Extract executable using tshark from PCAP file
      shell: |
        # Updated PCAP file path /tmp/captured.pcap
        tshark -r /tmp/captured.pcap -qz "follow,tcp,raw,0" > /tmp/extracted_executable.bin
      args:
        executable: /bin/bash
      register: extraction_result

    - name: Check if the extraction produced a file
      stat:
        path: /tmp/extracted_executable.bin
      register: extracted_file

    - name: Fail if no file was extracted
      fail:
        msg: "No executable was extracted from the PCAP file. Check the tshark command and PCAP file."
      when: not extracted_file.stat.exists

- name: Fetch the extracted executable to the Manage node
  hosts: localhost  # You can use localhost to fetch the file to the local machine
  tasks:
    - name: Fetch the extracted executable from the Control node
      fetch:
        src: /tmp/extracted_executable.bin
        dest: ./extracted_executable.bin
        flat: yes
      register: fetch_result

    - name: Show the fetch result
      debug:
        var: fetch_result
