---
- name: Install Tools & Extract Executable from PCAP
  hosts: servers
  become: yes
  tasks:
    - name: Ensure package list is updated
      apt:
        update_cache: yes

    - name: Install required tools
      apt:
        name:
          - wireshark
          - tcpdump
          - tshark
        state: present

    - name: Transfer PCAP file to Control Node
      copy:
        src: /tmp/captured.pcap
        dest: /tmp/captured.pcap
        remote_src: yes

    - name: Extract executables from PCAP using TShark
      shell: |
        tshark -r /tmp/captured.pcap --export-objects http,/tmp/extracted_files/
        tshark -r /tmp/captured.pcap --export-objects smb,/tmp/extracted_files/
        tshark -r /tmp/captured.pcap --export-objects ftp,/tmp/extracted_files/
      register: tshark_output

    - name: Show TShark extraction results
      debug:
        var: tshark_output.stdout_lines

    - name: Check if any files were extracted
      find:
        paths: /tmp/extracted_files/
      register: extracted_files

    - name: Report success or failure
      debug:
        msg: "Executable extracted successfully"
      when: extracted_files.matched > 0
